// vue/4-vue-props-emits/src/components/AddTodo.vue
<script setup lang="ts">
import { ref, defineEmits } from "vue";

const todoText = ref("");

const handleSubmit = () => {
  console.log("Submit", todoText.value);
  emit("createTodo", todoText.value);
  todoText.value = "";
};

const emit = defineEmits<{
  (e: "createTodo", text: string): void;
}>();
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" v-model="todoText" />
    <button>Spara</button>
  </form>
</template>

// react/2-react-props/src/components/AddTodo.tsx
import { FormEvent, useState } from "react";

interface IAddTodoProps {
  createShoppingItemInList: (text: string) => void;
}

export const AddTodo = ({ createShoppingItemInList }: IAddTodoProps) => {
  const [userInput, setUserInput] = useState("");

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    createShoppingItemInList(userInput);

    setUserInput("");
  };

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="text"
        value={userInput}
        onChange={(e) => setUserInput(e.target.value)}
      />
      <button type="submit">Spara</button>
    </form>
  );
};
