// vue/4-vue-props-emits/src/components/TodoApp.vue
<script setup lang="ts">
import Todos from "./Todos.vue";
import AddTodo from "./AddTodo.vue";
import { Todo } from "@/models/Todo";
import { ref } from "vue";

const todos = ref<Todo[]>([]);

const addTodo = (text: string) => {
  todos.value.push(new Todo(text));
};

const toggleTodo = (id: number) => {
  const foundTodo = todos.value.find((todo) => todo.id === id);
  if (foundTodo) {
    foundTodo.done = !foundTodo.done;
  }
};

const removeTodo = (id: number) => {
  const foundPosition = todos.value.findIndex((todo) => todo.id === id);
  if (foundPosition >= 0) todos.value.splice(foundPosition, 1);
};
</script>

<template>
  <AddTodo @create-todo="addTodo"></AddTodo>
  <Todos :todos="todos" @toggle-todo="toggleTodo" @remove-todo="removeTodo" />
</template>

// react/8-react-context-again/src/pages/TodoApp.tsx
import { useState } from "react";
import { Todo } from "../models/Todo";
import { AddTodo } from "../components/AddTodo";
import { TodoPresentation } from "../components/TodoPresentation";
import { TodosContext } from "../contexts/TodosContext";

export const TodoApp = () => {
  const [todos, setTodos] = useState<Todo[]>([new Todo("Test")]);

  const handleSave = (text: string) => {
    setTodos([...todos, new Todo(text)]);
  };

  const toggleTodo = (id: number) => {
    setTodos(
      todos.map((todo) => {
        if (todo.id === id) return { ...todo, done: !todo.done };
        else return todo;
      })
    );
  };

  const removeTodo = (id: number) => {
    setTodos(todos.filter((todo) => todo.id !== id));
  };

  return (
    <TodosContext.Provider
      value={{ todos, saveTodo: handleSave, toggleTodo, removeTodo }}
    >
      <AddTodo />

      <ul>
        <TodoPresentation />
      </ul>
    </TodosContext.Provider>
  );
};
